---
base_path: "/glade/work/rjarolim/spinn_me/spheromak_1_obs_v01"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/spheromak_1_obs_v01"

data:
  train_configs:
    - {type: 'hmi', data_path: "/glade/campaign/hao/radmhd/rjarolim/SPINN-ME/spheromak/simple_obs_060", stokes_normalization: 1.0, instrument_id: 'DEFAULT'}
  valid_config: {type: 'hmi', data_path: "/glade/campaign/hao/radmhd/rjarolim/SPINN-ME/spheromak/simple_obs_060", sample_idx: 49, stokes_normalization: 1.0, instrument_id: 'DEFAULT'}
  ref_time: "2025-01-01T00:00:00"
  num_workers: 16
  batch_size: 16384
  dataset_batch_size: 8192
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'phi'
    instrument_id: 'DEFAULT'

logging:
  project: pinn-me-spherical
  tags: ["spheromak"]
  name: "spheromak - 1 observers - v01"

model:
  type: mlp
  dim: 256
  n_layers: 6
  scale: true

training:
  epochs: 500
  check_val_every_n_epoch: 10

weight:
  I: 1.0
  Q: 1.0
  U: 1.0
  V: 1.0
