---
base_path: "/glade/work/rjarolim/spinn_me/test_set_v10"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/test_set_v09"
data:
  train_config: {data_path: "/glade/campaign/hao/radmhd/rjarolim/SPINN-ME/test_set/data"}
  valid_config: {data_path: "/glade/campaign/hao/radmhd/rjarolim/SPINN-ME/test_set/data", sample_idx: 49}
  ref_time: "2025-01-01T00:00:00"
  num_workers: 16
  batch_size: 65536
  stokes_normalization: 1
logging:
  project: pinn-me-spherical
  tags: ["test set"]
  name: "test set v01"
model:
  encoding: "gaussian"
training:
  epochs: 10000
  check_val_every_n_epoch: 10
  lambda_stokes: [10, 1, 1, 1]