---
base_path: "/glade/work/rjarolim/spinn_me/hmi/201102_6h_v01"
work_directory: "/glade/derecho/scratch/rjarolim/pinn_me/hmi/201102_6h_v01"
data:
  train_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/201102_6h"}
  valid_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/201102_6h", sample_idx: 7}
  ref_time: "2011-02-14T00:00:00"
  num_workers: 16
  batch_size: 262144
  dataset_batch_size: 8192
logging:
  project: pinn-me-spherical
  tags: ["hmi"]
  name: "2010-02 - 6h"
model:
  encoding: "gaussian"
training:
  epochs: 500
  check_val_every_n_epoch: 10