---
base_path: "/glade/work/rjarolim/spinn_me/hmi/202405_four_days_v03"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/202405_four_days_v01"
data:
  train_configs:
    - { type: 'hmi', data_path: "/glade/work/rjarolim/data/hmi_stokes/202405_12h", time_range: ["2024-05-05T12:00:00", "2024-05-09T12:00:00"], transmission_profile_directory: "/glade/work/rjarolim/data/hmi_calibration/202405", stokes_normalization: 5.0e+4, instrument_id: 'HMI' }
  valid_config: { type: 'hmi', data_path: "/glade/work/rjarolim/data/hmi_stokes/202405_12h/hmi.s_720s.20240507_120000_TAI.3.*.fits", transmission_profile_directory: "/glade/work/rjarolim/data/hmi_calibration/202405", stokes_normalization: 5.0e+4, instrument_id: 'HMI', resolution: [256, 256] }
  ref_time: "2024-05-07T12:00:00"
  num_workers: 8
  batch_size: 2048
  dataset_batch_size: 2048
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'hmi'
    instrument_id: 'HMI'
    limb_correction: False

logging:
  project: pinn-me-spherical
  tags: [ "hmi", "full-disk", "four-days", "no-physics" ]
  name: "2024-05 full-disk - four days centered on May 7"

model:
  type: mlp
  dim: 256
  n_layers: 6
  vector_potential: false
  scale: true
  activation: silu
  encoding_config: { type: fourier, num_frequencies: [64, 64, 64, 64], max_frequencies: [2048, 2048, 2048, 2048] }

training:
  epochs: 5000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  lr_params: { start: 1.0e-3, end: 1.0e-4, iterations: 2.0e+4 }

normalization:
  # Linear for weak polarization; compresses Q/U/V above 1% of the local continuum.
  asinh_alphas: { Q: 1.0e-3, U: 1.0e-3, V: 1.0e-3 }

weight:
  I: 1.0
  Q: 1.0
  U: 1.0
  V: 1.0
