---
base_path: "/glade/work/rjarolim/spinn_me/hmi/subframe_v09"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me_v2/hmi/subframe_v06"
data:
  train_configs:
    - { type: 'hmi', data_path: "/glade/work/rjarolim/data/phi_stokes/subframe", stokes_normalization: 5.0e+4, instrument_id: 'HMI' }
  valid_config: { type: 'hmi', data_path: "/glade/work/rjarolim/data/phi_stokes/subframe", sample_idx: 8, stokes_normalization: 5.0e+4, instrument_id: 'HMI' }
  ref_time: "2024-05-09T00:00:00"
  num_workers: 16
  batch_size: 65536
  dataset_batch_size: 1024
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'hmi'
    instrument_id: 'HMI'
    limb_correction: False
    velocity_correction: False

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "2024-03 subframe"

model:
  vector_potential: False
  encoding_config: {type: default, w0: 100}

training:
  epochs: 500
  lambda_stokes: [ 1, 1, 1, 1 ]
  lambda_induction: { start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }
  lambda_divergence: { start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }
  lambda_force_free: { start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }
  lambda_static: 0.0
#  lambda_gauge: 0.0