---
base_path: "/glade/work/rjarolim/spinn_me/hmi/201102_no_physics_v01"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me_v2/201102_physics_v09"
data:
  train_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/201102_3h"}
  valid_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/201102_3h", sample_idx: 20}
  ref_time: "2011-02-10T00:00:00"
  num_workers: 16
  batch_size: 32768
  dataset_batch_size: 8192
  seconds_per_dt: 864000 # 10 days
  gauss_per_dB: 1000
logging:
  project: pinn-me-spherical
  tags: ["hmi"]
  name: "2010-02 - 3h - no physics"
model:
  encoding: "gaussian"
training:
  epochs: 500
  lambda_stokes: [1, 1, 1, 1]
  lambda_induction: 0.0
  lambda_divergence: 0.0
  lambda_force_free: 0.0
  lambda_static: 0.0
#  val_check_interval: 1000