---
base_path: "/glade/work/rjarolim/spinn_me/hmi/202405_v01"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me_v2/hmi/202405_v01"
data:
  train_configs:
   - {data_path: "/glade/work/rjarolim/data/hmi_stokes/202405"}
  valid_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/202405", sample_idx: 20}
  ref_time: "2024-05-01T00:00:00"
  num_workers: 16
  batch_size: 32768
  dataset_batch_size: 8192
  seconds_per_dt: 864000 # 10 days
  gauss_per_dB: 1000
logging:
  project: pinn-me-spherical
  tags: ["hmi"]
  name: "2024-05"
model:
  encoding: "default"
  w0_initial: 100
training:
  epochs: 500
  lambda_stokes: [1, 1, 1, 1]
  lambda_induction: 0.0
  lambda_divergence: 0.0
  lambda_force_free: 0.0
  lambda_static: 0.0