---
base_path: "/glade/work/rjarolim/spinn_me/hmi/202405_90s_VP_v01"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me_v2/hmi/202405_90s_v08"
data:
  train_configs:
    - { type: 'hmi', data_path: "/glade/work/rjarolim/data/hmi_stokes/202405_90s", stokes_normalization: 5.0e+4, instrument_id: 'HMI' }
  valid_config: { type: 'hmi', data_path: "/glade/work/rjarolim/data/hmi_stokes/202405_90s", sample_idx: 8, stokes_normalization: 5.0e+4, instrument_id: 'HMI' }
  ref_time: "2024-05-09T00:00:00"
  num_workers: 16
  batch_size: 8192
  dataset_batch_size: 1024
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'hmi'
    instrument_id: 'HMI'

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "2024-05 90s no physics"

model:
  type: mlp
  dim: 256
  n_layers: 6
  vector_potential: true
  scale: true

training:
  epochs: 500
  val_check_interval: 5000

weight:
  I: 1.0
  Q: 2.0
  U: 2.0
  V: 2.0
