---
base_path: "/glade/work/rjarolim/spinn_me/hmi/202405_physics_v02"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me_v2/hmi/202405_physics_v02"
data:
  train_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/202405"}
  valid_config: {data_path: "/glade/work/rjarolim/data/hmi_stokes/202405", sample_idx: 20}
  ref_time: "2024-05-01T00:00:00"
  num_workers: 16
  batch_size: 65536
  dataset_batch_size: 8192
logging:
  project: pinn-me-spherical
  tags: ["hmi"]
  name: "2024-05"
model:
  encoding: "gaussian"
training:
  epochs: 500
  lambda_stokes: [1, 1, 1, 1]
  lambda_induction: 1.0e-4
  check_val_interval: 1000