---
base_path: "/glade/work/rjarolim/pinn_me/hmi/20100510_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/hmi/20100510_v01"
data:
  train_config: {data_path: "/glade/work/mmolnar/PINN-ME/HMI/HMI_20100510_720s"}
  valid_config: {data_path: "/glade/work/mmolnar/PINN-ME/HMI/HMI_20100510_720s", sample_idx: 5}
  num_workers: 16
  batch_size: 16384
logging:
  project: pinn-me-spherical
  tags: ["hmi"]
  name: "2010-05-10"
model:
  encoding: "gaussian"
training:
  epochs: 500
  check_val_every_n_epoch: 1