---
base_path: "/glade/work/rjarolim/spinn_me/hmi/phi_202403_v02"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/hmi/phi_202403_v01"
data:
  train_configs:
    - { type: 'phi-hrt', data_path: "/glade/work/rjarolim/data/phi_stokes/LB5/*.fits", stokes_normalization: 0.86205, instrument_id: 'PHI' }
  valid_config: { type: 'phi-hrt', data_path: "/glade/work/rjarolim/data/phi_stokes/LB5/*.fits", sample_idx: 5, stokes_normalization: 0.86205, instrument_id: 'PHI' }
  ref_time: "2024-03-23T22:30:00"
  num_workers: 16
  batch_size: 32768
  dataset_batch_size: 4096
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000
  stokes_normalization: 1.0

instrument:
  - type: 'phi'
    instrument_id: 'PHI'

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "2024-04 PHI"
model:
  encoding: "default"
  w0_initial: 100
training:
  epochs: 500
  lambda_stokes: [ 1, 2, 2, 2 ]
  lambda_induction: 0
  lambda_divergence: 0
  lambda_force_free: 0
  lambda_static: 0.0
  check_val_every_n_epoch: 5
#  val_check_interval: 2000