---
base_path: "/glade/work/rjarolim/spinn_me/hmi/phi_fdt_202403_v08"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/hmi/phi_fdt_202403_v02"
data:
  train_configs:
    - { type: 'phi-fdt', data_path: ["/glade/work/rjarolim/data/phi_fdt/2024-03-27/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-28/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-29/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-30/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-31/*.fits.gz"], stokes_normalization: 1.0, instrument_id: 'PHI' }
  valid_config: { type: 'phi-fdt', data_path: "/glade/work/rjarolim/data/phi_fdt/2024-03-29/*.fits.gz", sample_idx: 1, stokes_normalization: 1.0, instrument_id: 'PHI' }
  ref_time: "2024-03-27T00:00:00"
  num_workers: 16
  batch_size: 262144
  dataset_batch_size: 8192
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'phi'
    instrument_id: 'PHI'
    limb_correction: False
    artifact_correction: True

logging:
  project: pinn-me-spherical
  tags: [ "phi" ]
  name: "2024-04 PHI-FDT"

model:
  encoding_config: { type: positional, max_frequencies: [2.0, 8.0, 8.0, 8.0], num_frequencies: [16, 64, 64, 64] }#{ type: progressive_positional, max_frequencies: [1.0, 8.0, 8.0, 8.0], num_frequencies: [8, 32, 32, 32] }#{ type: spherical, scales: [1.0, 1.0, 128.0, 128.0, 128.0, 128.0], num_frequencies: [16, 0, 64, 64, 64, 64]}

training:
  epochs: 1000
  lambda_stokes: [ 10.0, 1.0, 1.0, 2.0 ]
  check_val_every_n_epoch: 50
  time_shift_config: {scale: 0.0, iterations: 0.0}