---
base_path: "/glade/work/rjarolim/spinn_me/hmi/phi_202403_v08"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/hmi/phi_202403_v08"
data:
  train_configs:
    - { type: 'phi-hrt', data_path: "/glade/work/rjarolim/data/phi_stokes/LB5/*.fits", stokes_normalization: 0.86205, instrument_id: 'PHI' }
  valid_config: { type: 'phi-hrt', data_path: "/glade/work/rjarolim/data/phi_stokes/LB5/*.fits", sample_idx: 5, stokes_normalization: 0.86205, instrument_id: 'PHI' }
  ref_time: "2024-03-23T22:30:00"
  num_workers: 16
  batch_size: 262144
  dataset_batch_size: 8192
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'phi'
    instrument_id: 'PHI'
    limb_correction: True
    velocity_correction: True
    artifact_correction: True

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "2024-04 PHI-HRT"

model:
  encoding_config: { type: gaussian, scales: [1.0, 128.0, 128.0, 128.0], num_frequencies: [16, 64, 64, 64]}

training:
  epochs: 10000
  lambda_stokes: [ 1.0, 1.0, 1.0, 1.0 ]
  check_val_every_n_epoch: 10
  time_shift_config: {scale: 0.0, iterations: 0.0}