---
base_path: "/glade/work/rjarolim/spinn_me/hmi/phi_fdt_202403_v08"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/hmi/phi_fdt_202403_v06"
data:
  train_configs:
    - { type: 'phi-fdt', data_path: ["/glade/work/rjarolim/data/phi_fdt/2024-03-27/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-28/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-29/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-30/*.fits.gz", "/glade/work/rjarolim/data/phi_fdt/2024-03-31/*.fits.gz"], stokes_normalization: 1.0, instrument_id: 'PHI' }
  valid_config: { type: 'phi-fdt', data_path: "/glade/work/rjarolim/data/phi_fdt/2024-03-27/*.fits.gz", sample_idx: 1, stokes_normalization: 1.0, instrument_id: 'PHI' }
  ref_time: "2024-03-27T00:00:00"
  num_workers: 16
  batch_size: 65536
  dataset_batch_size: 8192
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'phi'
    instrument_id: 'PHI'
    limb_correction: True
    velocity_correction: False

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "2024-04 PHI-FDT"
model:
  encoding_config: {type: spatiotemporal}


training:
  epochs: 500
  lambda_stokes: [ 1, 1, 1, 1 ]
  lambda_induction: 0 #{ start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }
  lambda_divergence: 0 #{ start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }
  lambda_force_free: 0 #{ start: 1.0e-2, end: 1.0e-6, iterations: 5.0e+4 }