---
base_path: "/glade/work/rjarolim/spinn_me/hmi/solar_cycle_v01"
work_directory: "/glade/derecho/scratch/rjarolim/spinn_me/solar_cycle_v01"
data:
  train_configs:
    - { type: 'hmi', data_path: "/glade/campaign/hao/radmhd/rjarolim/data_stash/solar_cycle", stokes_normalization: 5.0e+4, instrument_id: 'HMI', resolution: [256, 256]}
  valid_config: { type: 'hmi', data_path: "/glade/campaign/hao/radmhd/rjarolim/data_stash/solar_cycle", sample_idx: 500, stokes_normalization: 5.0e+4, instrument_id: 'HMI', resolution: [256, 256] }
  ref_time: "2011-01-01T00:00:00"
  num_workers: 16
  batch_size: 131072
  dataset_batch_size: 8192
  seconds_per_dt: 86400 # 1 day
  gauss_per_dB: 1000

instrument:
  - type: 'hmi'
    instrument_id: 'HMI'
    limb_correction: False

logging:
  project: pinn-me-spherical
  tags: [ "hmi" ]
  name: "Solar Cycle 2011 - 2013"

model:
  type: mlp
  dim: 512
  n_layers: 6
  scale: true

training:
  epochs: 1000
  check_val_every_n_epoch: 10

lambda:
  I: 1.0
  Q: 10.0
  U: 10.0
  V: 5.0
