---
base_path: "/glade/work/rjarolim/pinn_me/test_set/clear_v01"
data:
  type: "test"
  files: "/glade/campaign/hao/radmhd/rjarolim/PINN-ME/test_set/data/profile_*.npz"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  tags: ["test_set"]
  name: "clear"
model:
  dim: 256
  encoding: "gaussian_positional"

training:
  epochs: 100
  check_val_every_n_epoch: 5