---
base_path: "/glade/work/rjarolim/pinn_me/test_set/clear"
data:
  type: "test"
  files: "/glade/work/rjarolim/data/pinnme/test_set_400/profile_*.npz"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  group: "test_set"
  name: "clear"
model:
  dim: 256
  encoding: "positional"

training:
  epochs: 50
  check_val_every_n_epoch: 5