---
base_path: "/glade/work/rjarolim/pinn_me/hinode/hinode_psf_v02"
data:
  type: "hinode"
  files: "/glade/work/mmolnar/PINN-ME/Hinode/data/level1/2007/01/05/SP3D/20070105_235907/*.fits"
  num_workers: 8
  batch_size: 2048
logging:
  project: pinn-me
  group: "hinode"
  name: hinode PSF
model:
  encoding: "gaussian_positional"
training:
  epochs: 1000
  check_val_every_n_epoch: 5
  psf_config:
    type: load
    file: "/glade/work/rjarolim/data/inversion/hinode_psf_0.16.fits"
    crop: [18, -18, 18, -18]