---
base_path: "/glade/work/rjarolim/pinn_me/hinode/hinode_v02"
data:
  type: "hinode"
  files: "/glade/work/mmolnar/PINN-ME/Hinode/data/level1/2007/01/05/SP3D/20070105_235907/*.fits"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  group: "hinode"
  name: hinode
model:
  encoding: "gaussian_positional"
training:
  epochs: 1000
  check_val_every_n_epoch: 5