---
base_path: "/glade/work/rjarolim/pinn_me/muram/muram_gaussian_v01"
data:
  type: "fits"
  file: "/glade/work/rjarolim/data/pinnme/muram/SIRprofiles_plage.fits"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  name: muram gaussian v1
model:
  encoding: "gaussian_positional"
training:
  epochs: 1000
  check_val_every_n_epoch: 5