---
base_path: "/glade/work/rjarolim/pinn_me/test_set/psf_noise_{noise}_v02"
data:
  type: "test"
  files: "/glade/work/rjarolim/data/pinnme/test_set_400/profile_*.npz"
  psf: "/glade/work/rjarolim/data/inversion/hinode_psf_0.16.fits"
  noise: {noise}
  num_workers: 8
  batch_size: 2048
logging:
  project: pinn-me
  group: "test_set"
  name: "psf_noise_{noise}"
model:
  encoding: "positional"
training:
  epochs: 1000
  check_val_every_n_epoch: 5
  psf_config:
    type: load
    file: "/glade/work/rjarolim/data/inversion/hinode_psf_0.16.fits"
    crop: [18, -18, 18, -18]