---
base_path: "/glade/work/rjarolim/pinn_me/test_set/test_v02"
data:
  type: "test"
  files: "/glade/work/rjarolim/data/pinnme/test_set_400/profile_000.npz"
#  psf: "/glade/work/rjarolim/data/inversion/hinode_psf_0.16.fits"
#  noise: 1.0e-05
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  name: basic
model:
  dim: 256
  encoding: "positional"
#  psf_config:
#    type: load
#    file: "/glade/work/rjarolim/data/inversion/hinode_psf_0.16.fits"
training:
  epochs: 1000
  check_val_every_n_epoch: 5
