---
base_path: "/glade/work/rjarolim/pinn_me/hinode/hinode_v01"
data:
  type: "hinode"
  files: "/glade/campaign/hao/radmhd/rjarolim/PINN-ME/hinode/20070105_235907/*.fits"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  tags: ["hinode"]
  name: Hinode
model:
  encoding: "gaussian_positional"
training:
  epochs: 500
  check_val_every_n_epoch: 5