"""Pinned, checksum-verified scientific resources for LTE synthesis."""

from .manifest import (
    BUNDLE_TYPE,
    HINODE_PRODUCTION_FILES,
    HINODE_STIC_REQUIRED_DOMAIN_ANGSTROM,
    HINODE_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM,
    HMI_PRODUCTION_FILES,
    HMI_STIC_REQUIRED_DOMAIN_ANGSTROM,
    HMI_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM,
    REQUIRED_COMMON_PRODUCTION_FILES,
    REQUIRED_HINODE_PRODUCTION_FILES,
    REQUIRED_HMI_PRODUCTION_FILES,
    REFERENCE_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM,
    SUPPORTED_INSTRUMENTS,
    TRAINING_RESOURCE_CONTRACT,
    file_sha256,
    load_verified_source_manifest,
    resource_path,
    validate_resource_bundle,
    validate_instrument_resource_bundle,
    verify_manifest_resource,
)
from .registry import (
    AIA_RESOURCE_SET_ID,
    AIA_TEMPERATURE_RESPONSE_RESOURCE,
    LEGACY_LTE_RESOURCE_SET_ID,
    RESOURCE_SET_IDS,
    resolve_resource_reference,
    resource_set_path,
    validate_resource_set,
    validate_resource_sets,
)

__all__ = [
    "AIA_RESOURCE_SET_ID",
    "AIA_TEMPERATURE_RESPONSE_RESOURCE",
    "BUNDLE_TYPE",
    "HINODE_PRODUCTION_FILES",
    "HINODE_STIC_REQUIRED_DOMAIN_ANGSTROM",
    "HINODE_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM",
    "HMI_PRODUCTION_FILES",
    "HMI_STIC_REQUIRED_DOMAIN_ANGSTROM",
    "HMI_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM",
    "LEGACY_LTE_RESOURCE_SET_ID",
    "REQUIRED_COMMON_PRODUCTION_FILES",
    "REQUIRED_HINODE_PRODUCTION_FILES",
    "REQUIRED_HMI_PRODUCTION_FILES",
    "REFERENCE_STIC_REQUIRED_WAVELENGTH_NODES_ANGSTROM",
    "RESOURCE_SET_IDS",
    "SUPPORTED_INSTRUMENTS",
    "TRAINING_RESOURCE_CONTRACT",
    "file_sha256",
    "load_verified_source_manifest",
    "resolve_resource_reference",
    "resource_path",
    "resource_set_path",
    "validate_resource_set",
    "validate_resource_sets",
    "validate_resource_bundle",
    "validate_instrument_resource_bundle",
    "verify_manifest_resource",
]
