---
base_path: "/glade/work/rjarolim/pinn_me/muram/muram_sunspot_v04"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/hinode/muram_sunspot_v04"
data:
  type: "fits"
  file: "/glade/campaign/hao/radmhd/rjarolim/PINN-ME/muram/data/SIRprofiles_sunspot_v2.fits"
  num_workers: 8
  batch_size: 4096
logging:
  project: pinn-me
  name: muram sunspot
model:
  encoding: "gaussian_positional"
training:
  epochs: 100
  check_val_every_n_epoch: 5