---
base_path: "/glade/work/rjarolim/pinn_me/muram/muram_sunspot_psf_v01"
data:
  type: "fits"
  file: "/glade/campaign/hao/radmhd/rjarolim/PINN-ME/muram/data/SIRprofiles_sunspot.fits"
  num_workers: 8
  batch_size: 2048
logging:
  project: pinn-me
  name: muram sunspot psf
model:
  encoding: "gaussian_positional"
training:
  epochs: 200
  check_val_every_n_epoch: 5
  psf_config:
    type: load
    file: "/glade/campaign/hao/radmhd/rjarolim/PINN-ME/hinode_psf_0.16.fits"
    crop: [18, -18, 18, -18]